### ISSUE TITLE
Interactive, online analysis tool (devname: w_ipython)

### ISSUE THREAD

**Issue by astatide** [westpa/west_tools#18]
Hi all,

Inside of the DEVELOPMENT branch of west_tools, I've started work on an interactive tool to ease interactive and automated analysis; the current name is w_ipython.  I'm totally up for a different name.

The idea stemmed from the fact that we routinely needed to access the raw h5 data, either to debug a simulation or analyse it in a way that the tools don't currently (and probably won't ever) support.  It would have been nice, I figured, to have a script that would just load up the main h5 file (typically west.h5) and avoid having to do import numpy, h5py, load up the iterations, etc, and maybe throw in a few convenience functions.

It sort of grew from there.  It currently looks through the main configuration file (west.cfg), pulls in analysis parameters, runs functions that it needs to, and drops you at an ipython prompt with a 'w' object that contains all the information from your simulation and the analysis you've selected to do.

The initial and current development goals, as well as their implementation, are as follows.
- Ease analysis automation, in terms of reproducing the data, keeping track of analysis parameters, and in ensuring files from one analysis aren't accidentally used in other.
  1. To do this, it's using 'analysis schemes', specified in west.cfg.  These are simply parameters, underneath a name, for the main tools we use in analysis, with some 'these seem sane' defaults if the user hasn't specified anything.  When the tool is run, it parses through the schemes, tries to load all the files from the different schemes, and if it can't, runs the appropriate analysis (from the appropriate tool) with the work manager selected from the command prompt (so, whatever the current default is).  All files are stored in a subdir (specified by the user) in the simulation directory, and so the files won't interfere.
  2. This also enables us to conveniently scale out to clusters for analysis using the work manager (instead of w_run, you just call w_ipython).  Not that it was impossible before, but.
- Avoid having to use X.  We ship a few plotting tools, which is really quite nice, but it does mean an X server is required (or a way to ship files back and forth; the matplotlib backend agg IS available, but we don't use it by default).  Plothist/ploterr and then rsyncing can get a bit nasty, particularly when we just need a quick look at an evolution plot, not publication quality graphs.
- Easily analyse the simulation.  Currently, if you want to analyze anything from the h5 file, you'll need to use either h5py or hdfview (and only h5py if you want to run calculations on things).  If you want to plot data from an individual walker history, that also requires a set of scripts that we all probably have, but don't ship.  Here, there are a number of convenience functions, all set up in a 'stateful' manner:
  1. The user selects the iteration and analysis scheme they're interested in.
  2. Three 'iteration' objects are now available to the user: w.current, w.past, and w.future.
  3. Each 'iteration' object contains all the information from west.h5, assign.h5, stateprobs.h5, kintrace.h5, kinavg.h5, flux_matrices.h5, and kinrw.h5 (to use the default names) for the current iteration, in a convenient, easy to parse dictionary.  In addition, they're all keyed to the current segid; if you're interested in what walker 6 was doing in the past, pcoord wise, you'd simply call 'w.past['pcoord'][6]', and it'll sort out the appropriate parent information for you.  In addition, if you want to see what any future children of 6 are doing, you'd call 'w.future['pcoord'][6]', and it will return the pcoord information from the children of walker 6, assuming it has any.
  4. There's a convenient trace function, which pulls all information about the walker (weights, pcoord, auxdata, state information, bin information, etc) and returns it in a dictionary.  This makes it trivial to plot the weight or auxdata evolution of a particular trajectory, as an example.
  5. The plotting interface is currently limited to doing basic state probabilities (NOT using w_stateprobs information, at the moment) and plotting evolution plots (with CI), using either X or the terminal, for either kinavg or kinrw.  Calling 'w.help' should help elucidate this (and any other) information.

Some issues that would need to be ironed out before release:
1. The default parameters are set up as I found them convenient (which is cumulative evolution with a step size of 1).  This is probably more or less fine, but it means I hardcoded a few 'this is always going to be an evolution plot with a step size of 1' bits in here and there that I'd need to change.  It'll probably work with a bit of tweaking, but I should do said tweaking.
2. It can currently only construct rectilinear bin mappers, with code blatantly ripped from w_assign.  I should just call this function from w_assign to un-duplicate the code, or just think of a better way to do it altogether.
3. MORE DOCUMENTATION.

It's calling functionality from other code whenever it can, for the most part, so it should be easy enough to maintain.

A few screenshots or configuration options, for the unbelievers:

Inside my west.cfg:

```
  w_ipython:
    directory: ANALYSIS
    postanalysis: True
    w_kinavg:
      bootstrap: True
    analysis_schemes:
      BOUND:
        enabled: True
        states:
          - label: unbound
            coords: [[10.0]]
          - label: bound
            coords: [[3.99]]
        bins:
          - type: RectilinearBinMapper
            boundaries: [[0.0,4.0,10.00,100000]]
      NOCORREL:
        enabled: True
        w_kinavg:
          bootstrap: True
          correl: False
        states:
          - label: unbound
            coords: [[10.0]]
          - label: bound
            coords: [[3.99]]
        bins:
          - type: RectilinearBinMapper
            boundaries: [[0.0,4.0,10.00,100000]]
      PROB:
        enabled: True
        w_kinavg:
          bootstrap: True
          correl: False
        states:
          - label: unbound
            coords: [[10.0]]
          - label: bound
            coords: [[3.99]]
        bins:
          - type: RectilinearBinMapper
            boundaries: [[0.0,4.0,100000]]
```

Startup, selecting iteration, and what's available in the current iteration:
![screenshot from 2016-10-18 17-03-57](https://cloud.githubusercontent.com/assets/9011779/19496414/69eee06c-9555-11e6-999d-9881cdbe656e.png)

Plotting from state 0 to 1 from the reweighting code:
![screenshot from 2016-10-18 17-05-52](https://cloud.githubusercontent.com/assets/9011779/19496439/8328befe-9555-11e6-875c-d715f4007371.png)

Output from a trace.  Easily plotted with pyplot, if one chose to do so:

![screenshot from 2016-10-18 17-12-03](https://cloud.githubusercontent.com/assets/9011779/19496592/2cae6816-9556-11e6-8425-1f33046d380d.png)

Comments, suggestions, criticisms, design suggestions, usability concerns, etc, are all appreciated.  It's worth noting that all the tools have been updated such that they can run according to a particular 'analysis scheme' (in addition to their normal functionality), as well, so that it should be easy to integrate into an existing workflow.  One can also call the 'analyze only' flag, as well, to just run everything and call it a day.

Adam
